
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: live
    open-pull-requests-limit: 10
    reviewers:
      - chozandrias76
    labels:
      - "javascript"
      - "dependencies"
      - "automerge"
